### ISSUE TITLE
Can't build package  because scs update to new version

### ISSUE THREAD

**Issue by zhanglt** [zupzup/casbin-http-role-example#1]
The scs release to 1.3.0  , This package Can't build .
thanks!

**Comment by JamolHojahon** [comment]
Is some body gonna fix it or it's dead project? Thanks

**Comment by zupzup** [comment]
If you want to fix it, you're very welcome to. This is not a `project` per se, but as the title says, a code example for a blog post, so there is no plan to maintain it / update it to new versions.
