### ISSUE TITLE
ERROR: USER_NOT_FOUND

### ISSUE THREAD

**Issue by enzofoucaud** [zupzup/casbin-http-role-example#2]
Hello,

I try to go in localhost:8080/login but i have "WRONG_CREDENTIALS"
so i tried with this link localhost:8080/login?name=Admin and the same thing happens "WRONG_CREDENTIALS"

what did i miss ?

**Comment by zupzup** [comment]
Hey,

You need to send a form-data payload with a POST request to /login

You can use https://www.postman.com/ to create such a request, for example, but curl should also work: https://davidwalsh.name/curl-post-file

**Comment by enzofoucaud** [comment]
Ok ty, it's all good :)
